[versions]
agp = '8.3.1'
coroutines = '1.8.0'
composeCompiler = '1.4.7'
composeUi = '1.4.3'
javaTarget = '1.8'
kotlin = '1.8.21'
okhttp = '4.12.0'
okio = '3.2.0'
paparazzi = '1.3.1'

minSdk = '21'
compileSdk = '33'

[libraries]
androidx-annotations = { module = 'androidx.annotation:annotation', version = '1.7.1' }
androidx-core = { module = 'androidx.core:core', version = '1.10.1' }
androidx-cursorAdapter = { module = 'androidx.cursoradapter:cursoradapter', version = '1.0.0' }
androidx-exifInterface = { module = 'androidx.exifinterface:exifinterface', version = '1.3.7' }
androidx-fragment = { module = 'androidx.fragment:fragment', version = '1.6.2' }
androidx-junit = { module = 'androidx.test.ext:junit', version = '1.1.5' }
androidx-lifecycle = { module = 'androidx.lifecycle:lifecycle-common', version = '2.6.2' }
androidx-startup = { module = 'androidx.startup:startup-runtime', version = '1.1.1' }
androidx-testRunner = { module = 'androidx.test:runner', version = '1.5.2' }

coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = 'coroutines' }

composeUi = { module = 'androidx.compose.ui:ui', version.ref = 'composeUi' }
composeRuntime = { module = 'androidx.compose.runtime:runtime', version.ref = 'composeUi' }
composeUi-foundation = { module = 'androidx.compose.foundation:foundation', version.ref = 'composeUi' }
composeUi-material = { module = 'androidx.compose.material:material', version.ref = 'composeUi' }
composeUi-uiTooling = { module = 'androidx.compose.ui:ui-tooling', version.ref = 'composeUi' }
composeUi-test = { module = 'androidx.compose.ui:ui-test-junit4', version.ref = 'composeUi' }
composeUi-testManifest = { module = 'androidx.compose.ui:ui-test-manifest', version.ref = 'composeUi' }

drawablePainter = { module = 'com.google.accompanist:accompanist-drawablepainter', version = '0.30.1' }

okio = { module = "com.squareup.okio:okio", version = '3.9.0' }

okhttp = { module = 'com.squareup.okhttp3:okhttp', version.ref = 'okhttp' }
okhttp-mockWebServer = { module = 'com.squareup.okhttp3:mockwebserver', version.ref = 'okhttp' }

pollexor = { module = 'com.squareup:pollexor', version = '3.0.0' }

# Test libraries
junit = { module = 'junit:junit', version = '4.13.2' }
truth = { module = 'com.google.truth:truth', version = '1.4.2' }
robolectric = { module = 'org.robolectric:robolectric', version = '4.7' }
mockito = { module = 'org.mockito:mockito-core', version = '5.10.0' }

# Plugins
plugin-android = { module = 'com.android.tools.build:gradle', version.ref = 'agp' }
plugin-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version = '0.14.0' }
plugin-kotlin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }
plugin-paparazzi = { module = 'app.cash.paparazzi:paparazzi-gradle-plugin', version.ref = 'paparazzi' }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = '0.27.0' }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = '6.18.0' }
plugin-test-aggregation = { module = "io.github.gmazzo.test.aggregation:plugin", version = '2.2.0' }
